### ISSUE TITLE
[Bug] Homepage ad removal not working. Youtube vanced 

### ISSUE THREAD

**Issue by matthew745** [TeamVanced/Vanced#1796]
The homepage ad removal isn't working it shows ads on the home page i reinstall the app and turned on and off the feature and still doesn't work. I am using the latest version of youtube vanced on Samsung Galaxy S10.

Thanks!

**Comment by milindgoel15** [comment]
Blame Google

**Comment by matthew745** [comment]
> Blame Google

How is Google doing this?

**Comment by milindgoel15** [comment]
> How is Google doing this?

They roll out updates to their YouTube system server side adding new methods to display ads on home. This breaks the existing patches and hence, you see ads.

That's how ads are blocked on every version. We patched each possible ad with each release. But since, Google is now far ahead of the last vanced release and vanced being discontinued, there's no point of reporting any issue on this repository. 

And yes, blame Google because they added new ads system.

**Comment by matthew745** [comment]
> > How is Google doing this?
> 
> They roll out updates to their YouTube system server side adding new methods to display ads on home. This breaks the existing patches and hence, you see ads.
> 
> That's how ads are blocked on every version. We patched each possible ad with each release. But since, Google is now far ahead of the last vanced release and vanced being discontinued, there's no point of reporting any issue on this repository. Perhaps read the readme part of repositories before creating issues of any repo.
> 
> And yes, blame Google because they added new ads system.
Oh! Ok I am not against Google. Fuck Google!!
